services:
  redis:
    image: redis:latest
    restart: always

  scaleguard:
    build: .
    ports:
      - "5001:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    restart: always